### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by GoodMan0** [mzhaoshuai/RLCF#2]
Thanks for your interesting work. When do you release your code?

**Comment by mzhaoshuai** [comment]
@GoodMan0 
Thanks for approaching.

The code may be released after about 2 months in our plan.

We will inform u once it is released. :smile:

**Comment by mzhaoshuai** [comment]
Hi, @GoodMan0 , the code is open-sourced, please check https://github.com/mzhaoshuai/RLCF/tree/master.

I will close the issue, feel free to re-open.
