### ISSUE TITLE
the weight of ViT/L 14

### ISSUE THREAD

**Issue by cht619** [mzhaoshuai/RLCF#6]
Thanks for your wonderful work.  Can you share the weigh of ViT/L 14? since coop do not have ViT/L 14, dim=768

**Comment by mzhaoshuai** [comment]
Hi, thx for reaching out.

For TTA model, we do not use ViT-L/14. We use ViT-B/16.

![image](https://github.com/user-attachments/assets/0b502e17-c795-4634-8e41-7b9d69c68e7e)

For reward model, when using ViT-L/14, we use the original models from openai without further tuning.

**Comment by mzhaoshuai** [comment]
Close due to inactivity. Feel free to re-open.
